#define SCI_REG_PERIOD 0x00000005
#define SCI_REG_Digitizer_0_FIFOADDRESS 0x0
#define SCI_REG_Digitizer_0_STATUS 0x1
#define SCI_REG_Digitizer_0_INFO 0x2
#define SCI_REG_Digitizer_0_CONFIG 0x3
#define SCI_REG_Digitizer_0_ACQ_LEN 0x4

#define SCI_REG_Oscilloscope_0_FIFOADDRESS 0x400
#define SCI_REG_Oscilloscope_0_READ_STATUS 0x800
#define SCI_REG_Oscilloscope_0_READ_POSITION 0x801
#define SCI_REG_Oscilloscope_0_CONFIG_TRIGGER_MODE 0x802
#define SCI_REG_Oscilloscope_0_CONFIG_PRETRIGGER 0x803
#define SCI_REG_Oscilloscope_0_CONFIG_TRIGGER_LEVEL 0x804
#define SCI_REG_Oscilloscope_0_CONFIG_ARM 0x805
#define SCI_REG_Oscilloscope_0_CONFIG_DECIMATOR 0x806

